<%@ page language="C#" autoeventwireup="true" CodeFile="~/TrendCharts/FC3D/FC3D_DTHM.aspx.cs" inherits="Home_TrendCharts_FC3D_FC3D_DTHM" enableEventValidation="false" %>

<%@ Register Src="../../Home/Room/UserControls/Lotteries.ascx" TagName="Lotteries"
    TagPrefix="uc1" %>
<%@ Register Src="../../Home/Room/UserControls/TrendChartHead.ascx" TagName="TrendChartHead"
    TagPrefix="uc2" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>福彩3D 胆托号码速查表-彩票走势图表和数据分析－<%=_Site.Name %></title>
    <meta name="keywords" content="福彩3D 胆托号码速查表" />
    <meta name="description" content="福彩3D 胆托号码速查表、彩票走势图表和数据分析。" />
    <style type="text/css">
        .td
        {
            color: Red;
            font-size: 16px;
        }
        td
        {
            font-size: 12px;
            font-family: 宋体;
            text-align: center;
        }
        body
        {
            margin: 0px;
            margin-left: 10px;
            margin-right: 10px;
        }
        form
        {
            display: inline;
        }
        #box1
        {
            overflow: hidden;
            width: 1002px;
            margin-right: auto;
            margin-left: auto;
            padding: 0px;
        }
    </style>
    <link href="../../Home/Room/style/css.css" rel="stylesheet" type="text/css" />
     <link rel="shortcut icon" href="../../favicon.ico" />
</head>
<body>
    <form id="form1" runat="server">
    <asp:PlaceHolder ID="phHead" runat="server"></asp:PlaceHolder>
    <uc1:Lotteries ID="Lotteries1" runat="server" />
    <uc2:TrendChartHead ID="TrendChartHead1" runat="server" />
    <div id="box1">
        <table width="987" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
                <td class="td">
                    <h1 class="td" style="font-weight: bold; font-size: 18px;display:inline;">
                        3D胆托号码速查表走势图</h1>
                </td>
                <td style="background-color: White">
                    &nbsp;
                </td>
            </tr>
        </table>
        <div style="margin: 1px;">
        </div>
        <div id="div3" align="center">
            <table cellspacing="0" cellpadding="1" border="0" style="background-color: #cccccc;
                width: 987px; text-align: left; font-size: 12px;">
                <tr>
                    <td style="background-color: #EFEFEF; text-align: left; font-size: 12px;">
                        <a href="<%= _Site.Url %>" target="_blank" style="text-decoration: none; font-size: 14px;
                            padding-left: 10px;"><%=_Site.Name %>首页</a> <a href="<%= ResolveUrl("~/Lottery/Buy_3D.aspx") %>"
                                target="_blank" style="padding-left: 10px; text-decoration: none; color: Red;">福彩3D投注/合买</a>
                        <a href="<%= ResolveUrl("~/WinQuery/6-0-0.aspx") %>" target="_blank" style="padding-left: 10px;
                            text-decoration: none; color: Red;">福彩3D中奖查询</a>
                    </td>
                </tr>
            </table>
        </div>
        <div style="margin: 1px;">
        </div>
        <table width="987" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#666666">
            <tr>
                <td width="100%" align="center">
                    <table width="987" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tr>
                            <td height="10" style="background-color: White">
                                &nbsp;
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" valign="top">
                                <table cellspacing="1" cellpadding="1" bgcolor="#000000" border="0" width="987" align="center">
                                    <tbody>
                                        <tr align="center" bgcolor="#FFCC00">
                                            <td colspan="5" height="30">
                                                胆 0 的组合
                                            </td>
                                            <td width="35">
                                                000
                                            </td>
                                            <td colspan="5">
                                                胆 1 的组合
                                            </td>
                                            <td width="37">
                                                111
                                            </td>
                                            <td colspan="5">
                                                胆 2 的组合
                                            </td>
                                            <td width="36">
                                                222
                                            </td>
                                            <td colspan="5">
                                                胆 3 的组合
                                            </td>
                                            <td width="37">
                                                333
                                            </td>
                                            <td colspan="5">
                                                胆 4 的组合
                                            </td>
                                            <td width="37">
                                                444
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td width="105">
                                                001
                                            </td>
                                            <td>
                                                011
                                            </td>
                                            <td>
                                                012
                                            </td>
                                            <td width="35">
                                                024
                                            </td>
                                            <td width="35">
                                                037
                                            </td>
                                            <td>
                                                057
                                            </td>
                                            <td width="111">
                                                011
                                            </td>
                                            <td>
                                                001
                                            </td>
                                            <td>
                                                012
                                            </td>
                                            <td width="35">
                                                124
                                            </td>
                                            <td width="37">
                                                137
                                            </td>
                                            <td>
                                                157
                                            </td>
                                            <td width="111">
                                                022
                                            </td>
                                            <td>
                                                002
                                            </td>
                                            <td>
                                                012
                                            </td>
                                            <td width="37">
                                                124
                                            </td>
                                            <td width="37">
                                                237
                                            </td>
                                            <td>
                                                257
                                            </td>
                                            <td width="111">
                                                033
                                            </td>
                                            <td>
                                                003
                                            </td>
                                            <td>
                                                013
                                            </td>
                                            <td width="37">
                                                134
                                            </td>
                                            <td width="37">
                                                237
                                            </td>
                                            <td>
                                                357
                                            </td>
                                            <td width="111">
                                                044
                                            </td>
                                            <td>
                                                004
                                            </td>
                                            <td>
                                                014
                                            </td>
                                            <td width="37">
                                                134
                                            </td>
                                            <td width="37">
                                                247
                                            </td>
                                            <td>
                                                457
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                002
                                            </td>
                                            <td>
                                                022
                                            </td>
                                            <td>
                                                013
                                            </td>
                                            <td>
                                                025
                                            </td>
                                            <td>
                                                038
                                            </td>
                                            <td>
                                                058
                                            </td>
                                            <td>
                                                112
                                            </td>
                                            <td>
                                                122
                                            </td>
                                            <td>
                                                013
                                            </td>
                                            <td>
                                                125
                                            </td>
                                            <td>
                                                138
                                            </td>
                                            <td>
                                                158
                                            </td>
                                            <td>
                                                122
                                            </td>
                                            <td>
                                                112
                                            </td>
                                            <td>
                                                023
                                            </td>
                                            <td>
                                                125
                                            </td>
                                            <td>
                                                238
                                            </td>
                                            <td>
                                                258
                                            </td>
                                            <td>
                                                133
                                            </td>
                                            <td>
                                                113
                                            </td>
                                            <td>
                                                023
                                            </td>
                                            <td>
                                                135
                                            </td>
                                            <td>
                                                238
                                            </td>
                                            <td>
                                                358
                                            </td>
                                            <td>
                                                144
                                            </td>
                                            <td>
                                                114
                                            </td>
                                            <td>
                                                024
                                            </td>
                                            <td>
                                                145
                                            </td>
                                            <td>
                                                248
                                            </td>
                                            <td>
                                                458
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                003
                                            </td>
                                            <td>
                                                033
                                            </td>
                                            <td>
                                                014
                                            </td>
                                            <td>
                                                026
                                            </td>
                                            <td>
                                                039
                                            </td>
                                            <td>
                                                059
                                            </td>
                                            <td>
                                                113
                                            </td>
                                            <td>
                                                133
                                            </td>
                                            <td>
                                                014
                                            </td>
                                            <td>
                                                126
                                            </td>
                                            <td>
                                                139
                                            </td>
                                            <td>
                                                159
                                            </td>
                                            <td>
                                                223
                                            </td>
                                            <td>
                                                233
                                            </td>
                                            <td>
                                                024
                                            </td>
                                            <td>
                                                126
                                            </td>
                                            <td>
                                                239
                                            </td>
                                            <td>
                                                259
                                            </td>
                                            <td>
                                                233
                                            </td>
                                            <td>
                                                223
                                            </td>
                                            <td>
                                                034
                                            </td>
                                            <td>
                                                136
                                            </td>
                                            <td>
                                                239
                                            </td>
                                            <td>
                                                359
                                            </td>
                                            <td>
                                                244
                                            </td>
                                            <td>
                                                224
                                            </td>
                                            <td>
                                                034
                                            </td>
                                            <td>
                                                146
                                            </td>
                                            <td>
                                                249
                                            </td>
                                            <td>
                                                459
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                004
                                            </td>
                                            <td>
                                                044
                                            </td>
                                            <td>
                                                015
                                            </td>
                                            <td>
                                                027
                                            </td>
                                            <td>
                                                045
                                            </td>
                                            <td>
                                                067
                                            </td>
                                            <td>
                                                114
                                            </td>
                                            <td>
                                                144
                                            </td>
                                            <td>
                                                015
                                            </td>
                                            <td>
                                                127
                                            </td>
                                            <td>
                                                145
                                            </td>
                                            <td>
                                                167
                                            </td>
                                            <td>
                                                224
                                            </td>
                                            <td>
                                                244
                                            </td>
                                            <td>
                                                025
                                            </td>
                                            <td>
                                                127
                                            </td>
                                            <td>
                                                245
                                            </td>
                                            <td>
                                                267
                                            </td>
                                            <td>
                                                334
                                            </td>
                                            <td>
                                                344
                                            </td>
                                            <td>
                                                035
                                            </td>
                                            <td>
                                                137
                                            </td>
                                            <td>
                                                345
                                            </td>
                                            <td>
                                                367
                                            </td>
                                            <td>
                                                344
                                            </td>
                                            <td>
                                                334
                                            </td>
                                            <td>
                                                045
                                            </td>
                                            <td>
                                                147
                                            </td>
                                            <td>
                                                345
                                            </td>
                                            <td>
                                                467
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                005
                                            </td>
                                            <td>
                                                055
                                            </td>
                                            <td>
                                                016
                                            </td>
                                            <td>
                                                028
                                            </td>
                                            <td>
                                                046
                                            </td>
                                            <td>
                                                068
                                            </td>
                                            <td>
                                                115
                                            </td>
                                            <td>
                                                155
                                            </td>
                                            <td>
                                                016
                                            </td>
                                            <td>
                                                128
                                            </td>
                                            <td>
                                                146
                                            </td>
                                            <td>
                                                168
                                            </td>
                                            <td>
                                                225
                                            </td>
                                            <td>
                                                255
                                            </td>
                                            <td>
                                                026
                                            </td>
                                            <td>
                                                128
                                            </td>
                                            <td>
                                                246
                                            </td>
                                            <td>
                                                268
                                            </td>
                                            <td>
                                                335
                                            </td>
                                            <td>
                                                355
                                            </td>
                                            <td>
                                                036
                                            </td>
                                            <td>
                                                138
                                            </td>
                                            <td>
                                                346
                                            </td>
                                            <td>
                                                368
                                            </td>
                                            <td>
                                                445
                                            </td>
                                            <td>
                                                455
                                            </td>
                                            <td>
                                                046
                                            </td>
                                            <td>
                                                148
                                            </td>
                                            <td>
                                                346
                                            </td>
                                            <td>
                                                468
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                006
                                            </td>
                                            <td>
                                                066
                                            </td>
                                            <td>
                                                017
                                            </td>
                                            <td>
                                                029
                                            </td>
                                            <td>
                                                047
                                            </td>
                                            <td>
                                                069
                                            </td>
                                            <td>
                                                116
                                            </td>
                                            <td>
                                                166
                                            </td>
                                            <td>
                                                017
                                            </td>
                                            <td>
                                                129
                                            </td>
                                            <td>
                                                147
                                            </td>
                                            <td>
                                                169
                                            </td>
                                            <td>
                                                226
                                            </td>
                                            <td>
                                                266
                                            </td>
                                            <td>
                                                027
                                            </td>
                                            <td>
                                                129
                                            </td>
                                            <td>
                                                247
                                            </td>
                                            <td>
                                                269
                                            </td>
                                            <td>
                                                336
                                            </td>
                                            <td>
                                                366
                                            </td>
                                            <td>
                                                037
                                            </td>
                                            <td>
                                                139
                                            </td>
                                            <td>
                                                347
                                            </td>
                                            <td>
                                                369
                                            </td>
                                            <td>
                                                446
                                            </td>
                                            <td>
                                                466
                                            </td>
                                            <td>
                                                047
                                            </td>
                                            <td>
                                                149
                                            </td>
                                            <td>
                                                347
                                            </td>
                                            <td>
                                                469
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                007
                                            </td>
                                            <td>
                                                077
                                            </td>
                                            <td>
                                                018
                                            </td>
                                            <td>
                                                034
                                            </td>
                                            <td>
                                                048
                                            </td>
                                            <td>
                                                078
                                            </td>
                                            <td>
                                                117
                                            </td>
                                            <td>
                                                177
                                            </td>
                                            <td>
                                                018
                                            </td>
                                            <td>
                                                134
                                            </td>
                                            <td>
                                                148
                                            </td>
                                            <td>
                                                178
                                            </td>
                                            <td>
                                                227
                                            </td>
                                            <td>
                                                277
                                            </td>
                                            <td>
                                                028
                                            </td>
                                            <td>
                                                234
                                            </td>
                                            <td>
                                                248
                                            </td>
                                            <td>
                                                278
                                            </td>
                                            <td>
                                                337
                                            </td>
                                            <td>
                                                377
                                            </td>
                                            <td>
                                                038
                                            </td>
                                            <td>
                                                234
                                            </td>
                                            <td>
                                                348
                                            </td>
                                            <td>
                                                378
                                            </td>
                                            <td>
                                                447
                                            </td>
                                            <td>
                                                477
                                            </td>
                                            <td>
                                                048
                                            </td>
                                            <td>
                                                234
                                            </td>
                                            <td>
                                                348
                                            </td>
                                            <td>
                                                478
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                008
                                            </td>
                                            <td>
                                                088
                                            </td>
                                            <td>
                                                019
                                            </td>
                                            <td>
                                                035
                                            </td>
                                            <td>
                                                049
                                            </td>
                                            <td>
                                                079
                                            </td>
                                            <td>
                                                118
                                            </td>
                                            <td>
                                                188
                                            </td>
                                            <td>
                                                019
                                            </td>
                                            <td>
                                                135
                                            </td>
                                            <td>
                                                149
                                            </td>
                                            <td>
                                                179
                                            </td>
                                            <td>
                                                228
                                            </td>
                                            <td>
                                                288
                                            </td>
                                            <td>
                                                029
                                            </td>
                                            <td>
                                                235
                                            </td>
                                            <td>
                                                249
                                            </td>
                                            <td>
                                                279
                                            </td>
                                            <td>
                                                338
                                            </td>
                                            <td>
                                                388
                                            </td>
                                            <td>
                                                039
                                            </td>
                                            <td>
                                                235
                                            </td>
                                            <td>
                                                349
                                            </td>
                                            <td>
                                                379
                                            </td>
                                            <td>
                                                448
                                            </td>
                                            <td>
                                                488
                                            </td>
                                            <td>
                                                049
                                            </td>
                                            <td>
                                                245
                                            </td>
                                            <td>
                                                349
                                            </td>
                                            <td>
                                                479
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                009
                                            </td>
                                            <td>
                                                099
                                            </td>
                                            <td>
                                                023
                                            </td>
                                            <td>
                                                036
                                            </td>
                                            <td>
                                                056
                                            </td>
                                            <td>
                                                089
                                            </td>
                                            <td>
                                                119
                                            </td>
                                            <td>
                                                199
                                            </td>
                                            <td>
                                                123
                                            </td>
                                            <td>
                                                136
                                            </td>
                                            <td>
                                                156
                                            </td>
                                            <td>
                                                189
                                            </td>
                                            <td>
                                                229
                                            </td>
                                            <td>
                                                299
                                            </td>
                                            <td>
                                                123
                                            </td>
                                            <td>
                                                236
                                            </td>
                                            <td>
                                                256
                                            </td>
                                            <td>
                                                289
                                            </td>
                                            <td>
                                                339
                                            </td>
                                            <td>
                                                399
                                            </td>
                                            <td>
                                                123
                                            </td>
                                            <td>
                                                236
                                            </td>
                                            <td>
                                                356
                                            </td>
                                            <td>
                                                389
                                            </td>
                                            <td>
                                                449
                                            </td>
                                            <td>
                                                499
                                            </td>
                                            <td>
                                                124
                                            </td>
                                            <td>
                                                246
                                            </td>
                                            <td>
                                                456
                                            </td>
                                            <td>
                                                489
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td colspan="5">
                                                胆 5 的组合
                                            </td>
                                            <td>
                                                555
                                            </td>
                                            <td colspan="5">
                                                胆 6 的组合
                                            </td>
                                            <td>
                                                666
                                            </td>
                                            <td colspan="5">
                                                胆 7 的组合
                                            </td>
                                            <td>
                                                777
                                            </td>
                                            <td colspan="5">
                                                胆 8 的组合
                                            </td>
                                            <td>
                                                888
                                            </td>
                                            <td colspan="5">
                                                胆 9 的组合
                                            </td>
                                            <td>
                                                999
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                055
                                            </td>
                                            <td>
                                                005
                                            </td>
                                            <td>
                                                015
                                            </td>
                                            <td>
                                                135
                                            </td>
                                            <td>
                                                257
                                            </td>
                                            <td>
                                                457
                                            </td>
                                            <td>
                                                066
                                            </td>
                                            <td>
                                                006
                                            </td>
                                            <td>
                                                016
                                            </td>
                                            <td>
                                                136
                                            </td>
                                            <td>
                                                267
                                            </td>
                                            <td>
                                                467
                                            </td>
                                            <td>
                                                077
                                            </td>
                                            <td>
                                                007
                                            </td>
                                            <td>
                                                017
                                            </td>
                                            <td>
                                                137
                                            </td>
                                            <td>
                                                267
                                            </td>
                                            <td>
                                                467
                                            </td>
                                            <td>
                                                088
                                            </td>
                                            <td>
                                                008
                                            </td>
                                            <td>
                                                018
                                            </td>
                                            <td>
                                                138
                                            </td>
                                            <td>
                                                268
                                            </td>
                                            <td>
                                                468
                                            </td>
                                            <td>
                                                009
                                            </td>
                                            <td>
                                                099
                                            </td>
                                            <td>
                                                019
                                            </td>
                                            <td>
                                                139
                                            </td>
                                            <td>
                                                269
                                            </td>
                                            <td>
                                                469
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                155
                                            </td>
                                            <td>
                                                115
                                            </td>
                                            <td>
                                                025
                                            </td>
                                            <td>
                                                145
                                            </td>
                                            <td>
                                                258
                                            </td>
                                            <td>
                                                458
                                            </td>
                                            <td>
                                                166
                                            </td>
                                            <td>
                                                116
                                            </td>
                                            <td>
                                                026
                                            </td>
                                            <td>
                                                146
                                            </td>
                                            <td>
                                                268
                                            </td>
                                            <td>
                                                468
                                            </td>
                                            <td>
                                                177
                                            </td>
                                            <td>
                                                117
                                            </td>
                                            <td>
                                                027
                                            </td>
                                            <td>
                                                147
                                            </td>
                                            <td>
                                                278
                                            </td>
                                            <td>
                                                478
                                            </td>
                                            <td>
                                                188
                                            </td>
                                            <td>
                                                118
                                            </td>
                                            <td>
                                                028
                                            </td>
                                            <td>
                                                148
                                            </td>
                                            <td>
                                                278
                                            </td>
                                            <td>
                                                478
                                            </td>
                                            <td>
                                                119
                                            </td>
                                            <td>
                                                199
                                            </td>
                                            <td>
                                                029
                                            </td>
                                            <td>
                                                149
                                            </td>
                                            <td>
                                                279
                                            </td>
                                            <td>
                                                479
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                255
                                            </td>
                                            <td>
                                                225
                                            </td>
                                            <td>
                                                035
                                            </td>
                                            <td>
                                                156
                                            </td>
                                            <td>
                                                259
                                            </td>
                                            <td>
                                                459
                                            </td>
                                            <td>
                                                266
                                            </td>
                                            <td>
                                                226
                                            </td>
                                            <td>
                                                036
                                            </td>
                                            <td>
                                                156
                                            </td>
                                            <td>
                                                269
                                            </td>
                                            <td>
                                                469
                                            </td>
                                            <td>
                                                277
                                            </td>
                                            <td>
                                                227
                                            </td>
                                            <td>
                                                037
                                            </td>
                                            <td>
                                                157
                                            </td>
                                            <td>
                                                279
                                            </td>
                                            <td>
                                                479
                                            </td>
                                            <td>
                                                288
                                            </td>
                                            <td>
                                                228
                                            </td>
                                            <td>
                                                038
                                            </td>
                                            <td>
                                                158
                                            </td>
                                            <td>
                                                289
                                            </td>
                                            <td>
                                                489
                                            </td>
                                            <td>
                                                229
                                            </td>
                                            <td>
                                                299
                                            </td>
                                            <td>
                                                039
                                            </td>
                                            <td>
                                                159
                                            </td>
                                            <td>
                                                289
                                            </td>
                                            <td>
                                                489
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                355
                                            </td>
                                            <td>
                                                335
                                            </td>
                                            <td>
                                                045
                                            </td>
                                            <td>
                                                157
                                            </td>
                                            <td>
                                                345
                                            </td>
                                            <td>
                                                567
                                            </td>
                                            <td>
                                                366
                                            </td>
                                            <td>
                                                336
                                            </td>
                                            <td>
                                                046
                                            </td>
                                            <td>
                                                167
                                            </td>
                                            <td>
                                                346
                                            </td>
                                            <td>
                                                567
                                            </td>
                                            <td>
                                                377
                                            </td>
                                            <td>
                                                337
                                            </td>
                                            <td>
                                                047
                                            </td>
                                            <td>
                                                167
                                            </td>
                                            <td>
                                                347
                                            </td>
                                            <td>
                                                567
                                            </td>
                                            <td>
                                                388
                                            </td>
                                            <td>
                                                338
                                            </td>
                                            <td>
                                                048
                                            </td>
                                            <td>
                                                168
                                            </td>
                                            <td>
                                                348
                                            </td>
                                            <td>
                                                568
                                            </td>
                                            <td>
                                                339
                                            </td>
                                            <td>
                                                399
                                            </td>
                                            <td>
                                                049
                                            </td>
                                            <td>
                                                169
                                            </td>
                                            <td>
                                                349
                                            </td>
                                            <td>
                                                569
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                455
                                            </td>
                                            <td>
                                                445
                                            </td>
                                            <td>
                                                056
                                            </td>
                                            <td>
                                                158
                                            </td>
                                            <td>
                                                356
                                            </td>
                                            <td>
                                                568
                                            </td>
                                            <td>
                                                466
                                            </td>
                                            <td>
                                                446
                                            </td>
                                            <td>
                                                056
                                            </td>
                                            <td>
                                                168
                                            </td>
                                            <td>
                                                356
                                            </td>
                                            <td>
                                                568
                                            </td>
                                            <td>
                                                477
                                            </td>
                                            <td>
                                                447
                                            </td>
                                            <td>
                                                057
                                            </td>
                                            <td>
                                                178
                                            </td>
                                            <td>
                                                357
                                            </td>
                                            <td>
                                                578
                                            </td>
                                            <td>
                                                488
                                            </td>
                                            <td>
                                                448
                                            </td>
                                            <td>
                                                058
                                            </td>
                                            <td>
                                                178
                                            </td>
                                            <td>
                                                358
                                            </td>
                                            <td>
                                                578
                                            </td>
                                            <td>
                                                449
                                            </td>
                                            <td>
                                                499
                                            </td>
                                            <td>
                                                059
                                            </td>
                                            <td>
                                                179
                                            </td>
                                            <td>
                                                359
                                            </td>
                                            <td>
                                                579
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                556
                                            </td>
                                            <td>
                                                566
                                            </td>
                                            <td>
                                                057
                                            </td>
                                            <td>
                                                159
                                            </td>
                                            <td>
                                                357
                                            </td>
                                            <td>
                                                569
                                            </td>
                                            <td>
                                                566
                                            </td>
                                            <td>
                                                556
                                            </td>
                                            <td>
                                                067
                                            </td>
                                            <td>
                                                169
                                            </td>
                                            <td>
                                                367
                                            </td>
                                            <td>
                                                569
                                            </td>
                                            <td>
                                                577
                                            </td>
                                            <td>
                                                557
                                            </td>
                                            <td>
                                                067
                                            </td>
                                            <td>
                                                179
                                            </td>
                                            <td>
                                                367
                                            </td>
                                            <td>
                                                579
                                            </td>
                                            <td>
                                                588
                                            </td>
                                            <td>
                                                558
                                            </td>
                                            <td>
                                                068
                                            </td>
                                            <td>
                                                189
                                            </td>
                                            <td>
                                                368
                                            </td>
                                            <td>
                                                589
                                            </td>
                                            <td>
                                                559
                                            </td>
                                            <td>
                                                599
                                            </td>
                                            <td>
                                                069
                                            </td>
                                            <td>
                                                189
                                            </td>
                                            <td>
                                                369
                                            </td>
                                            <td>
                                                589
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                557
                                            </td>
                                            <td>
                                                577
                                            </td>
                                            <td>
                                                058
                                            </td>
                                            <td>
                                                235
                                            </td>
                                            <td>
                                                358
                                            </td>
                                            <td>
                                                578
                                            </td>
                                            <td>
                                                667
                                            </td>
                                            <td>
                                                677
                                            </td>
                                            <td>
                                                068
                                            </td>
                                            <td>
                                                236
                                            </td>
                                            <td>
                                                368
                                            </td>
                                            <td>
                                                678
                                            </td>
                                            <td>
                                                677
                                            </td>
                                            <td>
                                                667
                                            </td>
                                            <td>
                                                078
                                            </td>
                                            <td>
                                                237
                                            </td>
                                            <td>
                                                378
                                            </td>
                                            <td>
                                                678
                                            </td>
                                            <td>
                                                688
                                            </td>
                                            <td>
                                                668
                                            </td>
                                            <td>
                                                078
                                            </td>
                                            <td>
                                                238
                                            </td>
                                            <td>
                                                378
                                            </td>
                                            <td>
                                                678
                                            </td>
                                            <td>
                                                669
                                            </td>
                                            <td>
                                                699
                                            </td>
                                            <td>
                                                079
                                            </td>
                                            <td>
                                                239
                                            </td>
                                            <td>
                                                379
                                            </td>
                                            <td>
                                                679
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                558
                                            </td>
                                            <td>
                                                588
                                            </td>
                                            <td>
                                                059
                                            </td>
                                            <td>
                                                245
                                            </td>
                                            <td>
                                                359
                                            </td>
                                            <td>
                                                579
                                            </td>
                                            <td>
                                                668
                                            </td>
                                            <td>
                                                688
                                            </td>
                                            <td>
                                                069
                                            </td>
                                            <td>
                                                246
                                            </td>
                                            <td>
                                                369
                                            </td>
                                            <td>
                                                679
                                            </td>
                                            <td>
                                                778
                                            </td>
                                            <td>
                                                788
                                            </td>
                                            <td>
                                                079
                                            </td>
                                            <td>
                                                247
                                            </td>
                                            <td>
                                                379
                                            </td>
                                            <td>
                                                679
                                            </td>
                                            <td>
                                                788
                                            </td>
                                            <td>
                                                778
                                            </td>
                                            <td>
                                                089
                                            </td>
                                            <td>
                                                248
                                            </td>
                                            <td>
                                                389
                                            </td>
                                            <td>
                                                689
                                            </td>
                                            <td>
                                                779
                                            </td>
                                            <td>
                                                799
                                            </td>
                                            <td>
                                                089
                                            </td>
                                            <td>
                                                249
                                            </td>
                                            <td>
                                                389
                                            </td>
                                            <td>
                                                689
                                            </td>
                                        </tr>
                                        <tr align="center" bgcolor="#ffffff">
                                            <td>
                                                559
                                            </td>
                                            <td>
                                                599
                                            </td>
                                            <td>
                                                125
                                            </td>
                                            <td>
                                                256
                                            </td>
                                            <td>
                                                456
                                            </td>
                                            <td>
                                                589
                                            </td>
                                            <td>
                                                669
                                            </td>
                                            <td>
                                                699
                                            </td>
                                            <td>
                                                126
                                            </td>
                                            <td>
                                                256
                                            </td>
                                            <td>
                                                456
                                            </td>
                                            <td>
                                                689
                                            </td>
                                            <td>
                                                779
                                            </td>
                                            <td>
                                                799
                                            </td>
                                            <td>
                                                127
                                            </td>
                                            <td>
                                                257
                                            </td>
                                            <td>
                                                457
                                            </td>
                                            <td>
                                                789
                                            </td>
                                            <td>
                                                889
                                            </td>
                                            <td>
                                                899
                                            </td>
                                            <td>
                                                128
                                            </td>
                                            <td>
                                                258
                                            </td>
                                            <td>
                                                458
                                            </td>
                                            <td>
                                                789
                                            </td>
                                            <td>
                                                889
                                            </td>
                                            <td>
                                                899
                                            </td>
                                            <td>
                                                129
                                            </td>
                                            <td>
                                                259
                                            </td>
                                            <td>
                                                459
                                            </td>
                                            <td>
                                                789
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" height="19" bgcolor="#FFCC00">
                                <p>
                                    <br>
                                    <span class="bai">含有一个特定数字的三位数号码共有55注，其中有1注直选的“豹子”，18注“组选3“和36注“组选6”号码。如果将这个特定数字比作“胆”，则其胆拖的号码就有55注。根据“胆”号的奇偶，大小的不同，相应的组成号码又含有全奇，全偶，两奇一偶，两偶一奇，全大，全小，两大一小，两小一大的不同组合形式。比如以“0”为“胆”，其号码可组成全偶，全小，同时就不能组成全奇全大的形式。<br>
                                        根据对特定数字的出号状态，“组选3”，“组选6”中出情况的判断，即可进行“胆拖”选号了。
                                        <br>
                                        <br>
                                    </span>
                                </p>
                            </td>
                        </tr>
                        <tbody>
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>
        <div style="margin: 1px; text-align: left; font-size: 12px;">
            <table cellspacing="0" cellpadding="1" border="0" style="background-color: #cccccc;
                width: 100%; text-align: left;">
                <tr>
                    <td style="background-color: #EFEFEF; text-align: left;">
                        <a href="<%= _Site.Url %>" target="_blank"
                            style="text-decoration: none; font-size: 14px; padding-left: 10px;"><%=_Site.Name %>首页</a>
                        <a href="<%= ResolveUrl("~/Lottery/Buy_3D.aspx") %>" target="_blank" style="padding-left: 10px;
                            text-decoration: none; color: Red;">福彩3D投注/合买</a> <a href="<%= ResolveUrl("~/WinQuery/6-0-0.aspx") %>"
                                target="_blank" style="padding-left: 10px; text-decoration: none; color: Red;">福彩3D中奖查询</a>
                        <a href='FC3D_ZHXT.aspx' target='mainFrame'>综合分布遗漏走势图</a> | <a href='FC3D_C3YS.aspx'
                            target='mainFrame'>除三余数形态遗漏走势图</a> | <a href='FC3D_ZHZST.aspx' target='mainFrame'>质合形态遗漏走势图</a>
                        | <a href='FC3D_XTZST.aspx' target='mainFrame'>形态遗漏走势图</a> | <a href='FC3D_KDZST.aspx'
                            target='mainFrame'>跨度遗漏走势图</a> | <a href='FC3D_HZZST.aspx' target='mainFrame'>和值遗漏走势图</a>
                        | <a href='FC3D_DZXZST.aspx' target='mainFrame'>大中小形态遗漏走势图</a> | <a href='FC3D_C3YS_HTML.aspx'
                            target='mainFrame'>除三余数号码分区表走势图</a> |</br> <a href='FC3D_2CHW.aspx' target='mainFrame'>
                                二次和尾差尾查询表走势图</a> | <a href='FC3D_DSHM.aspx' target='mainFrame'>单双点号码分区表走势图</a>
                        <a href='FC3D_DTHM.aspx' target='mainFrame'>胆托号码分区表走势图</a> | <a href='FC3D_DX_JO.aspx'
                            target='mainFrame'>大小—奇偶号码分区表走势图</a> | <a href='FC3D_HSWH.aspx' target='mainFrame'>和数尾号码分区表走势图</a>
                        | <a href='FC3D_HSZ.aspx' target='mainFrame'>和数值号码分区表走势图</a> | <a href='FC3D_KDZH.aspx'
                            target='mainFrame'>跨度组合分区表走势图</a> | <a href='FC3D_JO_DX.aspx' target='mainFrame'>奇偶—大小号码分区表走势图</a>
                        | <a href='FC3D_LHZH.aspx' target='mainFrame'>连号组合分区表走势图</a> | <a href='FC3D_ZS.aspx'
                            target='mainFrame'>质数号码分区表走势图</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <asp:PlaceHolder ID="phFoot" runat="server"></asp:PlaceHolder>
    </form>
</body>
</html>
