//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP.Applications.TaobaoShopHelper.WebControls.Search {
    
    
    public partial class CtrlItem_Check {
        
        /// <summary>
        /// ucCtrlItemCheckImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TOP.Applications.TaobaoShopHelper.WebControls.Search.CtrlItem_Check_Image ucCtrlItemCheckImage;
        
        /// <summary>
        /// ucCtrlItemCheckList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TOP.Applications.TaobaoShopHelper.WebControls.Search.CtrlItem_Check_List ucCtrlItemCheckList;
    }
}
